<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestDemo1-DTT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4736193f-b5b5-4c60-acf2-d3bf5f5c9122</testSuiteGuid>
   <testCaseLink>
      <guid>47aef6d1-5f3a-4d93-9999-327a87957d51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DemoBlaze/LoginFunctionality</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>118ac01d-fb70-4008-a104-96653b837f63</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TEstSource1</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>118ac01d-fb70-4008-a104-96653b837f63</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>49fdee56-b945-4a32-982c-dc37d9c3f45f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>118ac01d-fb70-4008-a104-96653b837f63</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e7cd8743-b4bd-43cb-9264-d01f12f0b610</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
