<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Adress</name>
   <tag></tag>
   <elementGuidId>32b4c323-9246-4c1e-a281-61051dc3ec90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>xpath=//div[@id='currentAddress-wrapper']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
