<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CItyDemo</name>
   <tag></tag>
   <elementGuidId>52ed052b-7239-46cb-900b-18ba3a189f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>xpath=//div[@id='stateCity-wrapper']/div[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
