<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Month_month</name>
   <tag></tag>
   <elementGuidId>5995f390-5f81-44ae-baf2-553b11a9af5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27fb7720-4b68-4b2b-a8c9-1e75c457f9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af98623b-5ffb-4c37-9530-78f55bd83ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ab361c69-643d-4e70-9c2e-70fb58c270fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>93274215-23a0-443f-9969-dff30ede989c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;month&quot;)</value>
      <webElementGuid>ef6b264b-ea5c-4139-81f6-720cdb4a6644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='month']</value>
      <webElementGuid>46b1cc91-ab5c-446a-bf11-03ca3296b620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderModal']/div/div/div[2]/form/div[5]/input</value>
      <webElementGuid>8a52ef73-ea93-4fa9-b621-2113e9f1e6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>5efe8f3e-a27a-4b27-b7b4-a534ce1a0763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'month']</value>
      <webElementGuid>5819b6d5-7db9-408d-960c-e06d71ffb8a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
